version: '3.8'
services:
  falkordb:
    build: .
    ports:
     - "6379:6379"
     - "3001:3001"
    volumes:
     - "../files/falkordb-data:/var/lib/falkordb/data"
    restart: unless-stopped
    environment:
      - FALKORDB_ARGS=--port 6379 --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3